/* Compatibility API for the existing practice engines, backed only by this browser. */
window.PortalCloud=(()=>{'use strict';const S=LocalLearning,q=new URLSearchParams(location.search),lid=q.get('lesson'),pid=q.get('profile');let current={},dirty=false;
 const C={guest:false,role:'student',ready:false,contentLoaded:false,states:{},revisions:{},pending:{},conflicts:{},user:null,profile:null,packet:null,localError:false,failed:new Set()};
 const emit=()=>{const status=C.localError?'Chưa lưu được · thử lưu lại':'Đã lưu trên trình duyệt này';parent.postMessage({type:'portal-status',status,pending:C.localError},location.origin);['cloud-change','py-cloud-change','cpp-cloud-change'].forEach(k=>dispatchEvent(new Event(k)))};
 const getProjects=()=>S.projects(pid),setProjects=rows=>S.write('projects:'+pid,rows);
 C.init=async()=>{const p=S.profile(pid),l=STANDALONE.lessons.find(x=>x.key===lid);if(!p||!l)throw Error('local_profile_or_lesson_missing');C.profile={...p,student_code:''};C.user={id:pid};C.enrollment={enrollment_id:pid,run_id:S.course};const response=await fetch(new URL('../lessons/'+encodeURIComponent(lid)+'.json',location.href));if(!response.ok)throw Error('lesson_file_missing');const payload=await response.json();current=S.state(pid,lid);C.packet={course_id:S.course,run_id:S.course,enrollment_id:pid,lesson:{lesson_id:lid,lesson_key:lid,title:l.title,position:l.position,content_version:l.version||1},payload,progress:{state:current,revision:0},read_only:false};C.lessons=[C.packet.lesson];C.states[lid]=current;C.ready=C.contentLoaded=true;window.PORTAL_SELF_STUDY=true;window.PORTAL_FREE_NAV=false;window.PORTAL_SEQUENTIAL=true;emit();return C.packet};
 C.allowed=()=>C.ready&&Boolean(C.user);C.lessonId=k=>STANDALONE.lessons.some(l=>l.key===k)?k:null;C.content=()=>C.packet.payload;
 C.state=k=>C.failed.has(k)?C.states[k]:S.state(pid,k);C.peek=()=>C.failed.has(lid)?current:S.state(pid,lid);
 C.save=(key,state)=>{if(!C.allowed()||!C.lessonId(key))return false;state=S.copy(state);state.xp=Math.max(0,Number(state.xp)||0);C.allowDiscard=false;C.states[key]=state;if(key===lid)current=state;try{S.save(pid,key,state);C.failed.delete(key);if(state.completed||state.completedAt||state.dat)S.cert(pid,key,STANDALONE.lessons.find(l=>l.key===key).title)}catch{C.failed.add(key)}C.localError=dirty=C.failed.size>0;emit();return !C.failed.has(key)};
 C.confirmLeave=()=>{const child=document.querySelector('.q-khung.hien iframe')?.contentWindow?.PortalCloud;if(child)return child.confirmLeave();if(!C.localError||C.allowDiscard)return true;const ok=confirm('Bài chưa lưu được trên trình duyệt. Ở lại để thử lưu lại; tiếp tục rời bài sẽ bỏ phần chưa lưu.');if(ok)C.allowDiscard=true;return ok};C.flush=async()=>{for(const key of [...C.failed])C.save(key,C.states[key]);return !C.localError};C.controls=emit;C.setNestedPending=()=>{};
 C.download=()=>{S.download(S.backupName(pid),S.exportProfile(pid,{...Object.fromEntries([...C.failed].map(k=>[k,C.states[k]])),[lid]:C.peek()}));S.markExport(pid);parent.postMessage({type:'lsts-exported'},location.origin)};C.signOut=()=>parent.postMessage({type:'portal-account'},location.origin);
 C.client={rpc:async(name,p)=>{if(name==='learning_record_attempt'){const s=C.peek();C.save(lid,{...s,localAttempts:[...(s.localAttempts||[]),{id:p.p_attempt,payload:p.p_payload,at:new Date().toISOString()}].slice(-20)});return {data:{recorded:true},error:null}}if(name==='learning_save_progress'){C.save(lid,p.p_state);return {data:{state:C.peek(),revision:0},error:null}}if(name==='learning_enroll')return {data:C.enrollment,error:null};return {data:null,error:Error('Tính năng này không dùng trong chế độ lưu trình duyệt.')}}};
 C.practicePending=()=>0;C.flushPractice=async()=>true;C.practiceHistory=async key=>S.history(pid,key);C.logPractice=(key,kind,code,summary,snapshot)=>{try{S.practice(pid,key,{event_id:crypto.randomUUID(),kind,code:String(code||'').slice(0,32000),summary,snapshot_sql:snapshot,has_backup:!!snapshot,created_at:new Date().toISOString()});return true}catch{C.localError=true;emit();return false}};
 C.projectList=async()=>getProjects().map(p=>({...p,members:[{user_id:pid,display_name:C.profile.display_name,class_label:C.profile.class_label}],review:null}));C.projectGet=async id=>getProjects().find(p=>p.project_id===id);C.projectCreate=async(title,theme,group)=>{const p={project_id:crypto.randomUUID(),title,theme,group_label:group,status:'draft',payload:{},revision:0,submission_version:0,created_at:new Date().toISOString()};setProjects([...getProjects(),p]);return p.project_id};C.projectSave=async(project,payload,title,group)=>{const rows=getProjects(),p=rows.find(x=>x.project_id===project.project_id);if(!p)throw Error('Không tìm thấy dự án.');if(p.revision!==project.revision)return {conflict:true};p.payload=payload;p.title=title;p.group_label=group;p.revision++;setProjects(rows);return {revision:p.revision}};C.projectSubmit=async project=>{const rows=getProjects(),p=rows.find(x=>x.project_id===project.project_id);p.submission_version++;p.submitted_at=new Date().toISOString();setProjects(rows);S.download('du-an-'+p.submission_version+'.json',{...p,student:C.profile});return {ok:true}};C.projectSubmissions=async()=>[];
 addEventListener('message',async e=>{if(e.origin!==location.origin||e.source!==parent)return;const child=document.querySelector('.q-khung.hien iframe');if(child&&['portal-flush','portal-download'].includes(e.data?.type))return;if(e.data?.type==='portal-download')C.download();if(e.data?.type==='portal-flush'){await C.flush();emit()}});
 addEventListener('beforeunload',e=>{if(C.localError&&!C.allowDiscard){e.preventDefault();e.returnValue=''}});return C;
})();
