/* Each course owns its own browser profiles and progress. No account service. */
window.LocalLearning=(()=>{'use strict';
 const course=STANDALONE.course,ns='lsts-local:v1:'+course+':',copy=x=>JSON.parse(JSON.stringify(x));
 const read=(suffix,fallback)=>{try{return JSON.parse(localStorage.getItem(ns+suffix))??fallback}catch{return fallback}};
 const write=(suffix,value)=>{localStorage.setItem(ns+suffix,JSON.stringify(value));return value};
 const profiles=()=>read('profiles',[]),profile=id=>profiles().find(p=>p.id===id);
 const normalizeName=s=>String(s).replace(/\s+/g,' ').trim(),normalizeClass=s=>String(s).trim().toUpperCase();
 function check(name,cls){if(normalizeName(name).length<2)throw Error('Nhập họ và tên của em.');if(!normalizeClass(cls))throw Error('Nhập lớp học thuật.');if(course==='cpp-8-v2'&&!/^8A(?:[1-9]|10)$/.test(normalizeClass(cls)))throw Error('Chọn lớp từ 8A1 đến 8A10.')}
 function create(name,cls,chosen){name=normalizeName(name);cls=normalizeClass(cls);check(name,cls);const all=profiles();let p=chosen&&all.find(x=>x.id===chosen&&x.display_name===name&&x.class_label===cls);if(!p){p={id:crypto.randomUUID(),display_name:name,class_label:cls,created_at:new Date().toISOString()};all.push(p);write('profiles',all)}write('last-profile',p.id);return p}
 function edit(id,name,cls){check(name,cls);const all=profiles(),p=all.find(x=>x.id===id);if(!p)throw Error('Không tìm thấy người học.');p.display_name=normalizeName(name);p.class_label=normalizeClass(cls);write('profiles',all);return p}
 const key=(id,lesson)=>'progress:'+id+':'+lesson;
 const state=(id,lesson)=>read(key(id,lesson),{}),save=(id,lesson,value)=>write(key(id,lesson),value);
 const history=(id,lesson)=>read('practice:'+id+':'+lesson,[]),projects=id=>read('projects:'+id,[]);
 function practice(id,lesson,event){let rows=[event,...history(id,lesson)].slice(0,30),backups=0;rows=rows.filter(x=>!x.snapshot_sql||++backups<=3);while(rows.length>1&&new TextEncoder().encode(JSON.stringify(rows)).length>300000)rows.pop();return write('practice:'+id+':'+lesson,rows)}
 const download=(name,value,type='application/json')=>{const u=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
 function exportProfile(id,overrides={}){const p=profile(id);return {format:'lsts-local-backup',schema_version:1,course,profile:p,saved_at:new Date().toISOString(),lessons:Object.fromEntries(STANDALONE.lessons.map(l=>[l.key,overrides[l.key]||state(id,l.key)])),practice:Object.fromEntries(STANDALONE.lessons.map(l=>[l.key,history(id,l.key)])),projects:projects(id),certificates:read('certificates:'+id,{})}}
 function validateImport(v){if(v?.format!=='lsts-local-backup'||v.schema_version!==1||v.course!==course||!v.profile||!v.lessons||typeof v.lessons!=='object')throw Error('Bản sao không thuộc khóa này hoặc định dạng chưa hỗ trợ.');check(v.profile.display_name,v.profile.class_label);for(const [k,s] of Object.entries(v.lessons)){if(!STANDALONE.lessons.some(l=>l.key===k)||!s||typeof s!=='object'||Array.isArray(s)||JSON.stringify(s).length>512000)throw Error('Bản sao có bài hoặc dữ liệu không hợp lệ.')}return v}
 function importProfile(v){validateImport(v);const p=create(v.profile.display_name,v.profile.class_label,null);try{for(const [k,s] of Object.entries(v.lessons))save(p.id,k,s);for(const l of STANDALONE.lessons){const events=Array.isArray(v.practice?.[l.key])?v.practice[l.key].slice(0,30):[];write('practice:'+p.id+':'+l.key,events)}write('projects:'+p.id,Array.isArray(v.projects)?v.projects:[]);write('certificates:'+p.id,v.certificates&&typeof v.certificates==='object'?v.certificates:{});write('import-source:'+p.id,v.profile.id||'')}catch(e){throw Error('Bộ nhớ không đủ để nhập. Bản sao gốc và người học cũ vẫn được giữ.')}return p}
 function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16).toUpperCase().padStart(8,'0')}
 function legacy(p){const found={};for(const l of STANDALONE.lessons){let old=null;try{if(course==='cpp-8-v2'||course==='python-10'){const prefix=course==='cpp-8-v2'?'cpp8v2':'py10',id=hash((p.display_name+'|'+p.class_label).toLowerCase());old=JSON.parse(localStorage.getItem(prefix+':'+l.key+':'+id)||'null');if(!old?.student||normalizeName(old.student.name)!==p.display_name||normalizeClass(old.student.className)!==p.class_label)old=null}else if(course==='ml-level1'){old=JSON.parse(localStorage.getItem('ml1_'+l.key)||'null');if(normalizeName(old?.ten||'')!==p.display_name||normalizeClass(old?.lop||'')!==p.class_label)old=null}}catch{}if(old&&Object.keys(old).length&&!Object.keys(state(p.id,l.key)).length)found[l.key]=old}return found}
 function importLegacy(p,found){for(const [k,s] of Object.entries(found)){if(!Object.keys(state(p.id,k)).length)save(p.id,k,{...s,legacyImportedAt:new Date().toISOString()})}}
 function cert(id,lesson,title){let all=read('certificates:'+id,{});if(!all[lesson]){const p=profile(id);all[lesson]={id:hash(course+'|'+id+'|'+lesson),name:p.display_name,class_label:p.class_label,title,issued_at:new Date().toISOString()};write('certificates:'+id,all)}return all[lesson]}
 return {course,ns,read,write,profiles,profile,create,edit,state,save,history,practice,projects,download,exportProfile,validateImport,importProfile,legacy,importLegacy,cert,copy};
})();
