window.ActivityLesson=(C,p)=>{
 const S=LocalLearning,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),spec=p.payload.learning.assessment;
 const old=C.peek(),legacy=!!old.completed&&!old.completionPolicy;
 if(legacy)C.save(p.lesson.lesson_key,{...old,completionPolicy:'legacy-v1',legacyCompletionNote:'Hoàn thành theo điều kiện trước 08/10/2026; chưa kiểm tra lại checklist mới.'});
 document.body.innerHTML=`<main class="activity-page"><header><p class="learning-eyebrow">THỰC HÀNH · SẢN PHẨM VÀ MINH CHỨNG</p><h1>${esc(p.payload.title)}</h1><p>Làm nhiệm vụ trong notebook. Lưu nhật ký để giữ bài làm; tự xác nhận khi đủ sản phẩm và qua kiểm tra dưới đây.</p></header><article>${p.payload.html}</article><section class="learning-card" id="practice-assessment"><h2>Tự kiểm tra trước khi nộp</h2>${legacy||old.completionPolicy==='legacy-v1'?'<p class="learning-notice">Tiến độ trước đây được giữ nguyên. Con có thể hoàn thiện tiêu chí mới; chứng chỉ cũ ghi nhận điều kiện của phiên bản lúc cấp.</p>':''}<p>Đây là tự xác nhận quá trình học. Giáo viên đánh giá sản phẩm và minh chứng trên Canvas.</p><label for="activity-evidence">Nhật ký và link/tên tệp minh chứng</label><textarea id="activity-evidence" maxlength="6000" rows="6" placeholder="Đã làm gì? Kết quả nào minh chứng? Còn hạn chế gì? Ghi link hoặc tên tệp sản phẩm."></textarea><div class="learning-actions"><button id="activity-save">Lưu nhật ký</button><button id="activity-export">Tải minh chứng JSON</button></div><fieldset><legend>Checklist sản phẩm của buổi này</legend>${spec.criteria.map((x,i)=>`<label class="learning-check"><input type="checkbox" name="criterion" value="${i}"> ${esc(x)}</label>`).join('')}</fieldset><div class="activity-questions">${spec.questions.map(q=>`<fieldset><legend>${esc(q.q)}</legend>${q.options.map((x,i)=>`<label class="learning-check"><input type="radio" name="q-${esc(q.id)}" value="${i}"> ${esc(x)}</label>`).join('')}<p class="question-feedback" id="feedback-${esc(q.id)}" role="status"></p></fieldset>`).join('')}</div><button class="learning-primary" id="activity-complete">Kiểm tra và tự xác nhận hoàn thành</button><p id="activity-status" role="status"></p></section></main>`;
 const evidence=document.getElementById('activity-evidence'),state=C.peek();evidence.value=state.evidence||'';
 const review=state.practiceReview||{};
 document.querySelectorAll('[name=criterion]').forEach(e=>e.checked=!!review.criteria?.includes(Number(e.value)));
 for(const q of spec.questions){const e=document.querySelector(`[name="q-${q.id}"][value="${review.answers?.[q.id]}"]`);if(e)e.checked=true;}
 const hopes=spec.questions.map((q,i)=>HopeStars.mount(document.querySelectorAll('.activity-questions fieldset')[i],()=>C.peek(),'activity',q.id,!!C.peek().completed,st=>C.save(p.lesson.lesson_key,st)));
 const collect=()=>({criteria:[...document.querySelectorAll('[name=criterion]:checked')].map(e=>Number(e.value)),answers:Object.fromEntries(spec.questions.map(q=>[q.id,document.querySelector(`[name="q-${q.id}"]:checked`)?.value??null]))});
 const save=()=>C.save(p.lesson.lesson_key,{...C.peek(),evidence:evidence.value,started:true,practiceReview:collect()});
 evidence.addEventListener('input',save);document.querySelectorAll('#practice-assessment input').forEach(e=>e.addEventListener('change',save));
 document.getElementById('activity-save').onclick=()=>{document.getElementById('activity-status').textContent=save()?'Đã lưu nhật ký. Việc lưu chưa phải tự xác nhận hoàn thành.':'Chưa lưu được; ở lại và thử lưu lại.';};
 document.getElementById('activity-export').onclick=()=>S.download(p.lesson.lesson_key+'-minh-chung.json',{format:'lsts-practice-evidence',lesson:p.lesson.lesson_key,student:{name:C.profile.display_name,class_label:C.profile.class_label},evidence:evidence.value,review:collect(),assessment:'self-reported',saved_at:new Date().toISOString()});
 document.getElementById('activity-complete').onclick=()=>{
  const r=collect();let correct=0;
  for(const q of spec.questions){const ok=r.answers[q.id]!==null&&S.hash(q.id+'|'+r.answers[q.id])===q.answer_hash;if(r.answers[q.id]!==null)hopes[spec.questions.indexOf(q)].settle(ok);if(ok)correct++;document.getElementById('feedback-'+q.id).textContent=(ok?'✓ Đúng. ':'Cần xem lại. ')+q.why;}
  const ready=r.criteria.length===spec.criteria.length&&evidence.value.trim().length>=40&&correct===spec.questions.length;
  if(!ready){save();document.getElementById('activity-status').textContent=`Con cần đủ checklist, nhật ký/minh chứng có nội dung và đúng ${spec.questions.length}/${spec.questions.length} câu tự kiểm tra (hiện ${correct}). Tiến độ cũ được giữ.`;return;}
  const ok=C.save(p.lesson.lesson_key,{...C.peek(),evidence:evidence.value,practiceReview:{...r,correct,confirmed_at:new Date().toISOString()},started:true,completed:true,completedAt:C.peek().completedAt||new Date().toISOString(),completionPolicy:'practice-v2',completionBasis:'self-reported-checklist-and-quiz',xp:Math.max(C.peek().xp||0,30)});
  document.getElementById('activity-status').textContent=ok?'✓ Đã ghi nhận tự học theo checklist và kiểm tra. Tải minh chứng và nộp Canvas theo hướng dẫn giáo viên.':'Chưa lưu được; ở lại và thử lưu lại.';
 };
};
