window.LessonMissingTasks=(C,currentStage,rootForPanel)=>{
 const kind=C.packet.payload.kind,box=document.createElement('aside');box.id='learning-missing';box.className='learning-missing';box.setAttribute('aria-label','Việc còn thiếu');const info=document.createElement('span'),button=document.createElement('button');button.type='button';button.textContent='Đến nhiệm vụ chưa xong';box.append(info,button);
 const item=(el,label)=>el?{el,label}:null;
 function collect(){const s=C.peek(),st=currentStage();
  if(kind==='cpp'||kind==='python'){const step=LESSON.steps.find(x=>x.id===st.id);if(!step||step.kind==='extra')return [];return step.challenges.filter(x=>!x.bonus&&!x.advanced&&!x.extra&&!s.passed?.[x.id]).map(x=>item(document.querySelector(`[data-card="${x.id}"]`),x.title||x.name||'Nhiệm vụ')).filter(Boolean);}
  if(kind==='ml'){if(st.final?s.dat:s.passedStages?.includes(st.index))return [];return [...document.querySelectorAll('main .cau:not(.dung)')].map(el=>item(el,'Câu cần trả lời hoặc xem lại'));}
  if(kind==='sql'){if(s.completed)return [];if(st.index<4)return s.passed?.includes(st.index)?[]:[item(document.querySelector('#checkpoint'),'Checkpoint chặng '+(st.index+1))].filter(Boolean);if(st.index===4)return s.taskDone?[]:[item(document.querySelector('#sql'),'Kiểm tra nhiệm vụ SQL')].filter(Boolean);const qs=[...document.querySelectorAll('.quiz-item')];return qs.filter(el=>!el.querySelector('.feedback.good')).map(el=>item(el,'Câu cần trả lời hoặc xem lại'));}
  if(kind==='activity'){if(s.completed)return [];const result=[...document.querySelectorAll('[name=criterion]:not(:checked)')].map(el=>item(el,el.parentElement.textContent.trim()));const evidence=document.querySelector('#activity-evidence');if(evidence.value.trim().length<40)result.push(item(evidence,'Nhật ký và minh chứng (tối thiểu 40 ký tự)'));const spec=C.packet.payload.learning.assessment;spec.questions.forEach(q=>{const answer=document.querySelector(`[name="q-${q.id}"]:checked`);if(!answer||LocalLearning.hash(q.id+'|'+answer.value)!==q.answer_hash)result.push(item(document.querySelector(`[name="q-${q.id}"]`).closest('fieldset'),'Câu tự kiểm tra cần xem lại'));});return result.filter(Boolean);}
  return [];
 }
 let missing=[],timer;
 function update(){const root=rootForPanel();if(!root)return;if(!root.contains(box)){const overview=root.querySelector('#learning-overview');if(overview)overview.after(box);else root.prepend(box);}missing=collect();box.hidden=missing.length===0;const summary=missing.length+' mục còn thiếu · '+(missing[0]?.label||'');if(info.textContent!==summary)info.textContent=summary;}
 const schedule=()=>{clearTimeout(timer);timer=setTimeout(update,45);};
 button.onclick=()=>{update();const target=missing[0]?.el;if(!target)return;for(let p=target.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;target.classList.add('learning-target');target.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});const focus=target.matches('input,textarea,select,button')?target:target.querySelector('input,textarea,select,button')||target;if(!focus.matches('input,textarea,select,button'))focus.tabIndex=-1;focus.focus({preventScroll:true});setTimeout(()=>target.classList.remove('learning-target'),1800);};
 new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});addEventListener('cloud-change',schedule);document.addEventListener('input',schedule);document.addEventListener('change',schedule);update();
};
